name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject API base into config.js
        run: |
          mkdir -p ./docs
            echo "const apiBase = '${{ secrets.API_BASE }}';" > ./docs/config.js
            echo "Contents of config.js:"
            cat ./docs/config.js'

      - name: Debug API base secret
        run: echo "${{ secrets.API_BASE }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
